-- Demo catalog seed now lives in a migration so it applies to BOTH local
-- (`supabase db reset`) and cloud (`supabase db push`) identically.
-- See: supabase/migrations/20260710120100_seed_demo_catalog.sql
--
-- Keep this file empty to avoid double-inserting the catalog on local reset.
